/* eslint-disable react/no-unknown-property */

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/my-resume.glb -o src/components/ResumeCard.jsx -r public 
*/

import React, { useRef } from 'react'
import { Decal, useGLTF, useTexture, shaderMaterial } from '@react-three/drei'
import { extend } from '@react-three/fiber'
import * as THREE from 'three'

const color1 = new THREE.Color(0x78D5E1); // rgba(0,222,255,1)
const color2 = new THREE.Color(0x035BD4); // rgba(46,0,191,1)
const color3 = new THREE.Color(0x060094); // rgba(49,0,106,1)

const GradientShader = shaderMaterial(
	{
		u_color1: color1,
		u_color2: color2,
		u_color3: color3,
	},
	// Vertex Shader
	/* glsl */`
    varying vec2 vUv;

    void main() {
      vUv = uv;
      gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
    }
  `,
	// Fragment Shader
	/* glsl */
	`
    uniform vec3 u_color1;
    uniform vec3 u_color2;
    uniform vec3 u_color3;
    varying vec2 vUv;

    void main() {
      vec3 color = mix(u_color3, u_color1, smoothstep(0.0, 0.75, vUv.y));
      color = mix(color, u_color2, smoothstep(0.75, 1.0, vUv.y));
      gl_FragColor = vec4(color, 1.0);
    }
  `
);

extend({ GradientShader });

export function ResumeCard(props) {
	const { nodes, materials } = useGLTF('/models/my-resume.glb')
	const texture = useTexture('/models/cv.png')
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Cube.geometry}
				material={materials['Material.001']}
				position={[-0.441, 3.847, 0.064]}
				scale={[-0.236, -3.963, -6.421]}
				rotation={[0, 0, 0]}

			>
				<gradientShader attach="material" />

				<Decal
					position={[-1, 0, 0]} // Position of the decal
					rotation={[Math.PI / 2, Math.PI / 2, Math.PI / 2]} // Rotation of the decal (can be a vector or a degree in radians)
					scale={[1.9, 1.9, 1.97]} // Scale of the decal
				>
					<meshBasicMaterial map={texture}
						attach="material"
						polygonOffset
						polygonOffsetFactor={-1}
						transparent
					/>

				</Decal>
			</mesh>
		</group>
	)
}

useGLTF.preload('/models/my-resume.glb')
